config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  root 'welcome#index'

  get 'about' => 'welcome#about'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader

	geocoded_by :address
	after_validation :geocode

def address
	"#{city}, #{country}"
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    if params[:country] == nil
      @destinations = Destination.all
    else
      @destinations = Destination.where(country: params[:country])
    end
    @my_countries = Destination.select(:country).order(:country).distinct
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description, :population, 
                    :avatar, :latitude, :longitude)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@homestate = "Georgia"
  	@countries = ["Germany", "Australia", "Switzerland"]
		@images = ["bavaria2.jpg", "llamas.jpg", "alps.jpg", "kangaroo.jpg"]
		@image_hash = {"Bavaria" => "bavaria2.jpg", "Llamas" => "llamas.jpg",
								"Alps" => "alps.jpg", "Kangaroo" => "kangaroo.jpg"}

  end

  def about
  	@color = params[:color]
  	@size = params[:size].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
       <%= f.text_field :city, placeholder: "City", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :country, placeholder: "Country", class: "form-control" %>
  </div>
  <div>
    <%= f.number_field :population, placeholder: "Population", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder: "Description", class: "form-control" %>
  </div>
  <div class="form-group">
    <strong>Upload Image</strong>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Destinations</h1>

<ul class="nav nav-pills" role="tablist">
  <li><%= link_to "All", destinations_path %></li>
  <% @my_countries.each do |c| %>
    <li><%= link_to c.country, destinations_path(country: c.country) %></li>
  <% end %>
</ul>

<%= link_to 'New Destination', new_destination_path, class: "btn btn-info" %>

<div class = "row">
    <% @destinations.each do |destination| %>
      <div class = "col-md-4">
        <div class="well index-well">
          <h3><%= "#{destination.city}, #{destination.country}"%></h3>
          <% if destination.avatar.url == nil %>
            <%= image_tag "cityskyline.png", alt: "No image found", width: "200" %>
            <% else %>
          <p> <%= image_tag destination.avatar.url, alt: "#{destination.city}", width: "200" %></p>
          <% end %>
          <h4>Population: <%= number_with_delimiter destination.population %> </h4>
          <p><%= destination.description %></p>
          <p><%= link_to 'Show', destination %>
           <%= link_to 'Edit', edit_destination_path(destination) %>
            <%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %>
          </p>
        </div>
      </div>
    <% end %>
</div>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @destination.address %>
</h2>

<p><%= @destination.latitude%>, <%= @destination.longitude%></p>

<p>
	<strong>Population:</strong>
	<%= number_with_delimiter @destination.population %>
</p>


<p>
  <strong>Description:</strong>
  <%= @destination.description %>
</p>

<div id="destination-map"></div>

<p>
	<%= image_tag @destination.avatar.url, alt: "#{@destination.city}", width: "200" %>
</p>

<%= link_to 'Edit', edit_destination_path(@destination) %> |
<%= link_to 'Back', destinations_path %>

<%= javascript_tag do %>
   latitude = '<%= j @destination.latitude.to_s %>';
   longitude = '<%= j @destination.longitude.to_s %>';
   address = '<%= j @destination.address %>';
   description = '<%= j @destination.description %>';
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Travel</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <li><%= link_to "Home", root_path, class: "navbar-brand"%></li>
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Destinations", destinations_path %></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
<%= yield %>
</div>

 <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=<% ENV['google_api_key'] %>">
 </script>

</body>
</html>

app/views/welcome/about.html.erb
<style>
	body {
		background: <%= @color %>;
	}

</style>

<h1>About Me</h1>

<div id="map-canvas"></div>



<p>Look, a map!</p>
<p></p>
<p>My favorite color is <%= @color %></p>
<p>My shoe size is <%= @size %></p>

	<% if @size >= 12 %>
		<p> "My feet are <strong>huge</strong>!" </p>
	<%end%>
<p>

<%= link_to "Red", about_path(color: "red", size: 14), class: "btn btn-danger" %>
<%= link_to "Yellow", about_path(color: "yellow", size: 5), class: "btn btn-warning" %>
<%= link_to "Green", about_path(color: "green", size: 12), class: "btn btn-success" %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome to my Travel Site</h1>
<p>All about my awesome travels</p>
<p> I'm from <%= @homestate %></p>

<!-- puts each country from an array into an ordered list -->
<ol>
 <% @countries.each do |country| %>
			<li><%= country %></li>
			<% end %>
</ol>

<!-- Use a hash to show all the images with proper alts -->
<!-- if surround with p tags, on individual lines -->
<% @image_hash.each do |name, pic| %>
	<%= image_tag pic, alt: name, class: "img-responsive" %>
	<%end%>

<!-- puts each image from an array, no alts -->
<% @images.each do |pic| %>
	<p><%= image_tag pic, class: "img-responsive" %></p>
	<% end %>




<%#= image_tag "bavaria2.jpg", alt: "Castle" %>
<%#= image_tag "alps.jpg", alt: "Alps" %>
<%#= image_tag "llamas.jpg", alt: "Llamas" %>
<%#= image_tag "kangaroo.jpg", alt: "Kangaroo" %>